import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav: {
      events: 'Events',
      about: 'About',
      reserve: 'Reserve',
      home: 'Home',
      reserveSeat: 'Reserve a Seat',
      tagline: 'Where taste meets style',
    },
    hero: {
      eyebrow: 'Curated Editions · by Agnessitta',
      heading1: 'Where fashion meets',
      heading2: 'the art of',
      headingEm: 'dining',
      sub: 'Taste & Style by Agnessitta brings together the finest in fashion, food, and culture — intimate evenings crafted for those who live beautifully.',
      upcomingEditions: 'Upcoming Editions →',
      reserveSeat: 'Reserve a Seat',
      scrollExplore: 'Scroll to explore',
      nextEditionIn: 'Next edition in',
      days: 'Days',
      hrs: 'Hrs',
      min: 'Min',
      sec: 'Sec',
    },
    events: {
      bookNow: 'Book Now',
      joinWaitlist: 'Join Waitlist',
      notifyMe: 'Notify Me',
      viewRecap: 'View Recap',
      availability: 'Availability',
      spotsLeft: 'spots left',
      shareEvent: 'Share event',
      linkCopied: 'Link copied!',
      available: 'Available',
      limited: 'Limited Spots',
      soldOut: 'Sold Out',
      comingSoon: 'Coming Soon',
      pastEdition: 'Past Edition',
    },
    booking: {
      selectTicket: 'Select Ticket',
      yourDetails: 'Your Details',
      confirmed: 'Confirmed',
      chooseTicket: 'Choose your ticket',
      numberOfGuests: 'Number of guests',
      total: 'Total',
      cancel: 'Cancel',
      continue: 'Continue →',
      back: '← Back',
      completeReservation: 'Complete Reservation',
      firstName: 'First Name',
      lastName: 'Last Name',
      emailAddress: 'Email Address',
      phone: 'Phone',
      dietary: 'Dietary Requirements',
      optional: '(optional)',
      terms: 'I agree to the',
      termsLink: 'Terms & Conditions',
      and: 'and',
      privacyLink: 'Privacy Policy',
      reservationConfirmed: 'Reservation confirmed!',
      confirmationSent: 'Your confirmation has been sent to',
      lookForward: 'We look forward to welcoming you.',
      date: 'Date',
      venue: 'Venue',
      ticket: 'Ticket',
      totalPaid: 'Total Paid',
      guest: 'Guest',
      reference: 'Reference',
      done: 'Done',
    },
  },
  pl: {
    nav: {
      events: 'Wydarzenia',
      about: 'O nas',
      reserve: 'Rezerwuj',
      home: 'Strona główna',
      reserveSeat: 'Zarezerwuj miejsce',
      tagline: 'Gdzie smak spotyka styl',
    },
    hero: {
      eyebrow: 'Kolekcjonowane edycje · by Agnessitta',
      heading1: 'Gdzie moda spotyka',
      heading2: 'sztukę',
      headingEm: 'gotowania',
      sub: 'Taste & Style by Agnessitta łączy to, co najlepsze w modzie, jedzeniu i kulturze — kameralne wieczory stworzone dla tych, którzy żyją pięknie.',
      upcomingEditions: 'Nadchodzące edycje →',
      reserveSeat: 'Zarezerwuj miejsce',
      scrollExplore: 'Przewiń, aby odkryć',
      nextEditionIn: 'Kolejna edycja za',
      days: 'Dni',
      hrs: 'Godz',
      min: 'Min',
      sec: 'Sek',
    },
    events: {
      bookNow: 'Rezerwuj',
      joinWaitlist: 'Lista oczekujących',
      notifyMe: 'Powiadom mnie',
      viewRecap: 'Zobacz podsumowanie',
      availability: 'Dostępność',
      spotsLeft: 'miejsc pozostało',
      shareEvent: 'Udostępnij',
      linkCopied: 'Link skopiowany!',
      available: 'Dostępne',
      limited: 'Ograniczona liczba',
      soldOut: 'Wyprzedane',
      comingSoon: 'Wkrótce',
      pastEdition: 'Zakończona edycja',
    },
    booking: {
      selectTicket: 'Wybierz bilet',
      yourDetails: 'Twoje dane',
      confirmed: 'Potwierdzone',
      chooseTicket: 'Wybierz swój bilet',
      numberOfGuests: 'Liczba gości',
      total: 'Razem',
      cancel: 'Anuluj',
      continue: 'Dalej →',
      back: '← Wróć',
      completeReservation: 'Zakończ rezerwację',
      firstName: 'Imię',
      lastName: 'Nazwisko',
      emailAddress: 'Adres e-mail',
      phone: 'Telefon',
      dietary: 'Wymagania dietetyczne',
      optional: '(opcjonalnie)',
      terms: 'Zgadzam się z',
      termsLink: 'Regulaminem',
      and: 'i',
      privacyLink: 'Polityką prywatności',
      reservationConfirmed: 'Rezerwacja potwierdzona!',
      confirmationSent: 'Potwierdzenie zostało wysłane na adres',
      lookForward: 'Nie możemy się doczekać, aby Cię powitać.',
      date: 'Data',
      venue: 'Miejsce',
      ticket: 'Bilet',
      totalPaid: 'Zapłacono',
      guest: 'Gość',
      reference: 'Numer rezerwacji',
      done: 'Gotowe',
    },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
