import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    marquee: [
      'Fashion Forward', 'Fine Dining', 'Curated Editions', 'London',
      'Exclusive Experiences', 'Style Conversations', 'By Agnessitta',
      'La Dolce Afro', 'Valentine Opulence', 'Culture & Community',
    ],
    gallery: {
      label: 'Visual Stories',
      heading: 'From past',
      headingEm: 'editions',
      captions: ['Evening Guests', 'La Dolce Afro', 'Brand Gifting', 'Fashion Circle', 'Style Editorial', 'Portrait', 'The Collective', 'Runway Ready', 'Front Row', 'Sweet Finale'],
    },
    stats: {
      items: [
        { value: '4', label: 'Cities' },
        { value: '360+', label: 'Guests Hosted' },
        { value: '3', label: 'Years of Excellence' },
        { value: '7', label: 'Editions Curated' },
      ],
    },
    story: {
      label: 'Our Origin',
      heading: 'Born from a belief that the most memorable experiences happen at the intersection of two worlds.',
      body1: 'In April 2024, 80 guests gathered in a converted industrial space in Warsaw. There was a chef, a designer, and an idea: that what we eat and what we wear tell the same story. That evening sold out in four days and ended at 2am with no one wanting to leave.',
      body2: 'That was Edition I. Since then, we\'ve hosted seven intimate evenings across four Polish cities, earned coverage in Vogue Polska and Harper\'s Bazaar, and built a community of guests who return edition after edition.',
      quote: '"We don\'t curate events. We create the conditions for something genuinely unexpected to happen."',
      soldOut: 'Sold out rate',
      rating: 'Average guest rating',
      returnGuests: 'Return guests',
      sellout: 'Average sell-out time',
    },
    testimonials: {
      label: 'Guest Stories',
      heading: 'What our guests',
      headingEm: 'say',
      items: [
        { quote: "An evening I'll carry with me for years. The dinner was poetry, the fashion was theatre, and the conversation was everything in between.", name: 'Magda T.', role: 'Creative Director, Warsaw', edition: 'Warsaw Summer Edition' },
        { quote: "Taste & Style has created something entirely new — not a dinner, not a show, but a genuine cultural moment. I've attended every edition since the first.", name: 'Piotr K.', role: 'Architect, Kraków', edition: 'Kraków Autumn Edition' },
        { quote: "The most beautifully curated evening I've attended in Poland. Every detail — the table, the lighting, the music between courses — spoke of deep intention.", name: 'Aleksandra W.', role: 'Fashion Editor, Warsaw', edition: 'Warsaw Summer Edition' },
        { quote: "I came for the food, stayed for the fashion, and left with three new friendships I still have. That's the real Taste & Style magic.", name: 'Tomasz R.', role: 'Restaurateur, Poznań', edition: 'Poznań Winter Edition' },
      ],
    },
    upcoming: {
      label: 'This Season',
      heading: 'Upcoming',
      headingEm: 'Editions',
      viewAll: 'View All Events',
    },
    newsletter: {
      label: 'Inner Circle',
      heading: 'Be the first to know about',
      headingBr: 'the next',
      headingEm: 'edition',
      sub: 'Early access to reservations, curator announcements, and exclusive previews — for those on our private list.',
      placeholder: 'Your email address',
      cta: 'Join the List',
      successText: 'You\'re on the list. We\'ll be in touch before the next edition opens.',
      noSpam: 'No spam. Unsubscribe at any time.',
    },
    insta: {
      handle: '@tasteandstyle.official',
      follow: 'Follow us',
    },
    footer: {
      tagline: 'Where taste meets style,\nedition after edition.',
      colEditions: 'Editions',
      upcoming: 'Upcoming Events',
      past: 'Past Editions',
      story: 'Our Story',
      colInfo: 'Info',
      contact: 'Contact',
      press: 'Press & Media',
      private: 'Private Events',
      colLegal: 'Legal',
      privacy: 'Privacy Policy',
      terms: 'Terms & Conditions',
      cookies: 'Cookies',
      rights: 'All rights reserved.',
      curated: 'Curated Editions · by Agnessitta',
    },
    eventsPage: {
      label: 'Our Editions',
      heading: 'Every city.\nEvery season.\nOne',
      headingEm: 'ethos',
      sub: 'From Warsaw to Gdańsk, Taste & Style hosts intimate evenings at the intersection of haute cuisine and fashion.',
      filterAll: 'All',
      filterUpcoming: 'Upcoming',
      filterPast: 'Past',
      cityAll: 'All',
      emptyState: 'No editions match this filter.',
      clearFilters: 'Clear filters',
    },
    about: {
      manifestoLabel: 'Our Manifesto',
      manifestoQuote: '"Born from a belief that the most memorable evenings happen when fashion and food share the same table."',
      manifestoSub: 'Style and taste. Culture and community. London and beyond.',
      originLabel: 'Our Origin',
      originHeading: 'How it began.',
      originBody1: 'It started with a vision. Agnessitta believed that the best evenings happen when fashion, food, and culture collide — not in separate rooms, but at the same table. In April 2024, that vision became Edition I: 80 guests at Orzo Restaurant, an evening that ended at 2am with no one wanting to leave.',
      originBody2: 'That first evening sold out within days. The second in hours. By Edition III, the red dress code and IBRA gifting had become iconic. Taste & Style had become something more than an event — it had become a movement.',
      originBlockquote: '"Every edition is curated from scratch — every detail, every guest, every moment. That\'s the Taste & Style promise."',
      valuesLabel: 'What We Stand For',
      valuesHeading: 'Three principles.',
      valuesHeadingEm: 'One ethos.',
      values: [
        { number: 'I', title: 'Intentionality', text: 'Every detail is deliberate — from the dress code to the centrepiece. Nothing happens by accident at a Taste & Style edition.' },
        { number: 'II', title: 'Intimacy', text: 'We keep our editions small by design. Curated guest lists. No festival crowds — just a room full of people who truly belong there.' },
        { number: 'III', title: 'Excellence', text: 'We work only with the best — celebrated chefs, luxury brand partners, and fashion talent that is redefining modern style.' },
      ],
      timelineLabel: 'Edition History',
      timelineHeading: 'Every edition.',
      timelineHeadingEm: 'Every city.',
      timelineGuests: 'guests',
      ctaHeading: 'Ready to experience the next',
      ctaHeadingEm: 'edition',
      ctaSub: 'Seats are limited and sell out fast. Reserve your place at the table.',
      ctaBtn: 'View Upcoming Editions',
      ctaContact: 'Get in Touch',
    },
    recap: {
      allEditions: 'All Editions',
      editionLabel: 'Edition',
      recapLabel: 'Recap',
      guests: 'guests',
      eveningHighlights: 'Evening Highlights',
      onTheNight: 'On the Night',
      ctaText: 'Want to be part of the next edition?',
      ctaBtn: 'View Upcoming Editions →',
      notFound: 'Edition not found.',
      backToEvents: '← Back to Events',
    },
    nav: {
      events: 'Events',
      about: 'About',
      reserve: 'Reserve',
      home: 'Home',
      reserveSeat: 'Reserve a Seat',
      tagline: 'Where taste meets style',
    },
    hero: {
      eyebrow: 'Curated Editions · by Agnessitta',
      heading1: 'Where fashion meets',
      heading2: 'the art of',
      headingEm: 'dining',
      sub: 'Taste & Style by Agnessitta brings together the finest in fashion, food, and culture — intimate evenings crafted for those who live beautifully.',
      upcomingEditions: 'Upcoming Editions →',
      reserveSeat: 'Reserve a Seat',
      scrollExplore: 'Scroll to explore',
      nextEditionIn: 'Next edition in',
      days: 'Days',
      hrs: 'Hrs',
      min: 'Min',
      sec: 'Sec',
    },
    events: {
      bookNow: 'Book Now',
      joinWaitlist: 'Join Waitlist',
      notifyMe: 'Notify Me',
      viewRecap: 'View Recap',
      availability: 'Availability',
      spotsLeft: 'spots left',
      shareEvent: 'Share event',
      linkCopied: 'Link copied!',
      available: 'Available',
      limited: 'Limited Spots',
      soldOut: 'Sold Out',
      comingSoon: 'Coming Soon',
      pastEdition: 'Past Edition',
    },
    booking: {
      selectTicket: 'Select Ticket',
      yourDetails: 'Your Details',
      confirmed: 'Confirmed',
      chooseTicket: 'Choose your ticket',
      numberOfGuests: 'Number of guests',
      total: 'Total',
      cancel: 'Cancel',
      continue: 'Continue →',
      back: '← Back',
      completeReservation: 'Complete Reservation',
      firstName: 'First Name',
      lastName: 'Last Name',
      emailAddress: 'Email Address',
      phone: 'Phone',
      dietary: 'Dietary Requirements',
      optional: '(optional)',
      terms: 'I agree to the',
      termsLink: 'Terms & Conditions',
      and: 'and',
      privacyLink: 'Privacy Policy',
      reservationConfirmed: 'Reservation confirmed!',
      confirmationSent: 'Your confirmation has been sent to',
      lookForward: 'We look forward to welcoming you.',
      date: 'Date',
      venue: 'Venue',
      ticket: 'Ticket',
      totalPaid: 'Total Paid',
      guest: 'Guest',
      reference: 'Reference',
      done: 'Done',
    },
  },
  pl: {
    marquee: [
      'Moda i Styl', 'Wykwintna Kuchnia', 'Kolekcjonowane Edycje', 'Londyn',
      'Ekskluzywne Doświadczenia', 'Rozmowy o Stylu', 'By Agnessitta',
      'La Dolce Afro', 'Valentine Opulence', 'Kultura i Wspólnota',
    ],
    gallery: {
      label: 'Historie wizualne',
      heading: 'Z poprzednich',
      headingEm: 'edycji',
      captions: ['Wieczorni Goście', 'La Dolce Afro', 'Prezenty Marki', 'Krąg Mody', 'Redakcja Stylu', 'Portret', 'Kolektyw', 'Gotowi na Wybieg', 'Pierwszy Rząd', 'Słodki Finał'],
    },
    stats: {
      items: [
        { value: '4', label: 'Miasta' },
        { value: '360+', label: 'Gości' },
        { value: '3', label: 'Lata Doskonałości' },
        { value: '7', label: 'Edycji' },
      ],
    },
    story: {
      label: 'Nasza Historia',
      heading: 'Zrodzone z przekonania, że najbardziej niezapomniane doświadczenia dzieją się na styku dwóch światów.',
      body1: 'W kwietniu 2024 roku 80 gości zebrało się w przerobionym industrialnym wnętrzu w Warszawie. Był szef kuchni, projektant i idea: że to, co jemy i co nosimy, opowiada tę samą historię. Tamten wieczór wyprzedał się w ciągu czterech dni i zakończył o 2 w nocy — nikt nie chciał wychodzić.',
      body2: 'To była Edycja I. Od tamtej pory zorganizowaliśmy siedem kameralnych wieczorów w czterech polskich miastach, zdobyliśmy uwagę Vogue Polska i Harper\'s Bazaar, i zbudowaliśmy społeczność gości, którzy wracają edycja po edycji.',
      quote: '"Nie organizujemy wydarzeń. Tworzymy warunki, w których może zdarzyć się coś naprawdę nieoczekiwanego."',
      soldOut: 'Wskaźnik wyprzedania',
      rating: 'Średnia ocena gości',
      returnGuests: 'Powracający goście',
      sellout: 'Średni czas wyprzedania',
    },
    testimonials: {
      label: 'Opinie Gości',
      heading: 'Co mówią nasi',
      headingEm: 'goście',
      items: [
        { quote: 'Wieczór, który będę nosić w sobie przez lata. Kolacja była poezją, moda — teatrem, a rozmowa — wszystkim pomiędzy.', name: 'Magda T.', role: 'Dyrektor Kreatywna, Warszawa', edition: 'Edycja Letnia, Warszawa' },
        { quote: 'Taste & Style stworzyło coś zupełnie nowego — nie kolację, nie show, ale prawdziwy moment kulturowy. Byłem na każdej edycji od pierwszej.', name: 'Piotr K.', role: 'Architekt, Kraków', edition: 'Edycja Jesienna, Kraków' },
        { quote: 'Najpiękniej skomponowany wieczór, na jakim byłam w Polsce. Każdy detal — stół, oświetlenie, muzyka między daniami — świadczył o głębokiej intencji.', name: 'Aleksandra W.', role: 'Redaktorka Mody, Warszawa', edition: 'Edycja Letnia, Warszawa' },
        { quote: 'Przyszłam dla jedzenia, zostałam dla mody, a wyszłam z trzema przyjaźniami, które mam do dziś. To właśnie magia Taste & Style.', name: 'Tomasz R.', role: 'Restaurator, Poznań', edition: 'Edycja Zimowa, Poznań' },
      ],
    },
    upcoming: {
      label: 'Ten Sezon',
      heading: 'Nadchodzące',
      headingEm: 'Edycje',
      viewAll: 'Zobacz Wszystkie',
    },
    newsletter: {
      label: 'Krąg Wtajemniczonych',
      heading: 'Bądź pierwsza/-y, która/-y dowie się o',
      headingBr: 'kolejnej',
      headingEm: 'edycji',
      sub: 'Wczesny dostęp do rezerwacji, ogłoszenia kuratorów i ekskluzywne podglądy — dla osób na naszej prywatnej liście.',
      placeholder: 'Twój adres e-mail',
      cta: 'Dołącz do listy',
      successText: 'Jesteś na liście. Skontaktujemy się przed otwarciem kolejnej edycji.',
      noSpam: 'Zero spamu. Możesz zrezygnować w każdej chwili.',
    },
    insta: {
      handle: '@tasteandstyle.official',
      follow: 'Obserwuj nas',
    },
    footer: {
      tagline: 'Gdzie smak spotyka styl,\nedycja po edycji.',
      colEditions: 'Edycje',
      upcoming: 'Nadchodzące wydarzenia',
      past: 'Minione edycje',
      story: 'Nasza historia',
      colInfo: 'Informacje',
      contact: 'Kontakt',
      press: 'Prasa i Media',
      private: 'Wydarzenia prywatne',
      colLegal: 'Prawne',
      privacy: 'Polityka prywatności',
      terms: 'Regulamin',
      cookies: 'Cookies',
      rights: 'Wszelkie prawa zastrzeżone.',
      curated: 'Kolekcjonowane Edycje · by Agnessitta',
    },
    eventsPage: {
      label: 'Nasze Edycje',
      heading: 'Każde miasto.\nKażdy sezon.\nJeden',
      headingEm: 'etos',
      sub: 'Od Warszawy po Gdańsk — Taste & Style organizuje kameralne wieczory na styku haute cuisine i mody.',
      filterAll: 'Wszystkie',
      filterUpcoming: 'Nadchodzące',
      filterPast: 'Minione',
      cityAll: 'Wszystkie',
      emptyState: 'Brak edycji pasujących do filtra.',
      clearFilters: 'Wyczyść filtry',
    },
    about: {
      manifestoLabel: 'Nasz Manifest',
      manifestoQuote: '"Zrodzone z przekonania, że najpiękniejsze wieczory zdarzają się, gdy moda i jedzenie dzielą ten sam stół."',
      manifestoSub: 'Styl i smak. Kultura i wspólnota. Londyn i nie tylko.',
      originLabel: 'Nasze Początki',
      originHeading: 'Jak to się zaczęło.',
      originBody1: 'Zaczęło się od wizji. Agnessitta wierzyła, że najpiękniejsze wieczory zdarzają się, gdy moda, jedzenie i kultura spotykają się — nie w osobnych salach, lecz przy tym samym stole. W kwietniu 2024 roku ta wizja stała się Edycją I: 80 gości w Orzo Restaurant, wieczór, który zakończył się o 2 w nocy i nikt nie chciał wychodzić.',
      originBody2: 'Ten pierwszy wieczór wyprzedał się w ciągu kilku dni. Drugi — w kilka godzin. W Edycji III czerwony dress code i gifting IBRA stały się ikoniczne. Taste & Style przestało być wydarzeniem — stało się ruchem.',
      originBlockquote: '"Każda edycja jest tworzona od zera — każdy detal, każdy gość, każda chwila. To jest obietnica Taste & Style."',
      valuesLabel: 'Co Wyznajemy',
      valuesHeading: 'Trzy zasady.',
      valuesHeadingEm: 'Jeden etos.',
      values: [
        { number: 'I', title: 'Intencjonalność', text: 'Każdy detal jest przemyślany — od dress code\'u po dekorację stołu. W Taste & Style nic nie dzieje się przypadkowo.' },
        { number: 'II', title: 'Kameralność', text: 'Nasze edycje są celowo małe. Starannie dobrane listy gości. Żadnych tłumów — tylko sala pełna ludzi, którzy naprawdę tam przynależą.' },
        { number: 'III', title: 'Doskonałość', text: 'Współpracujemy tylko z najlepszymi — cenionymi szefami kuchni, luksusowymi partnerami i talentami modowymi, które redefiniują nowoczesny styl.' },
      ],
      timelineLabel: 'Historia Edycji',
      timelineHeading: 'Każda edycja.',
      timelineHeadingEm: 'Każde miasto.',
      timelineGuests: 'gości',
      ctaHeading: 'Gotowy/-a na kolejną',
      ctaHeadingEm: 'edycję',
      ctaSub: 'Miejsca są ograniczone i sprzedają się szybko. Zarezerwuj swoje miejsce przy stole.',
      ctaBtn: 'Zobacz nadchodzące edycje',
      ctaContact: 'Skontaktuj się',
    },
    recap: {
      allEditions: 'Wszystkie edycje',
      editionLabel: 'Edycja',
      recapLabel: 'Podsumowanie',
      guests: 'gości',
      eveningHighlights: 'Wieczorne Momenty',
      onTheNight: 'Tego Wieczoru',
      ctaText: 'Chcesz być częścią kolejnej edycji?',
      ctaBtn: 'Zobacz nadchodzące edycje →',
      notFound: 'Nie znaleziono edycji.',
      backToEvents: '← Powrót do wydarzeń',
    },
    nav: {
      events: 'Wydarzenia',
      about: 'O nas',
      reserve: 'Rezerwuj',
      home: 'Strona główna',
      reserveSeat: 'Zarezerwuj miejsce',
      tagline: 'Gdzie smak spotyka styl',
    },
    hero: {
      eyebrow: 'Kolekcjonowane edycje · by Agnessitta',
      heading1: 'Gdzie moda spotyka',
      heading2: 'sztukę',
      headingEm: 'gotowania',
      sub: 'Taste & Style by Agnessitta łączy to, co najlepsze w modzie, jedzeniu i kulturze — kameralne wieczory stworzone dla tych, którzy żyją pięknie.',
      upcomingEditions: 'Nadchodzące edycje →',
      reserveSeat: 'Zarezerwuj miejsce',
      scrollExplore: 'Przewiń, aby odkryć',
      nextEditionIn: 'Kolejna edycja za',
      days: 'Dni',
      hrs: 'Godz',
      min: 'Min',
      sec: 'Sek',
    },
    events: {
      bookNow: 'Rezerwuj',
      joinWaitlist: 'Lista oczekujących',
      notifyMe: 'Powiadom mnie',
      viewRecap: 'Zobacz podsumowanie',
      availability: 'Dostępność',
      spotsLeft: 'miejsc pozostało',
      shareEvent: 'Udostępnij',
      linkCopied: 'Link skopiowany!',
      available: 'Dostępne',
      limited: 'Ograniczona liczba',
      soldOut: 'Wyprzedane',
      comingSoon: 'Wkrótce',
      pastEdition: 'Zakończona edycja',
    },
    booking: {
      selectTicket: 'Wybierz bilet',
      yourDetails: 'Twoje dane',
      confirmed: 'Potwierdzone',
      chooseTicket: 'Wybierz swój bilet',
      numberOfGuests: 'Liczba gości',
      total: 'Razem',
      cancel: 'Anuluj',
      continue: 'Dalej →',
      back: '← Wróć',
      completeReservation: 'Zakończ rezerwację',
      firstName: 'Imię',
      lastName: 'Nazwisko',
      emailAddress: 'Adres e-mail',
      phone: 'Telefon',
      dietary: 'Wymagania dietetyczne',
      optional: '(opcjonalnie)',
      terms: 'Zgadzam się z',
      termsLink: 'Regulaminem',
      and: 'i',
      privacyLink: 'Polityką prywatności',
      reservationConfirmed: 'Rezerwacja potwierdzona!',
      confirmationSent: 'Potwierdzenie zostało wysłane na adres',
      lookForward: 'Nie możemy się doczekać, aby Cię powitać.',
      date: 'Data',
      venue: 'Miejsce',
      ticket: 'Bilet',
      totalPaid: 'Zapłacono',
      guest: 'Gość',
      reference: 'Numer rezerwacji',
      done: 'Gotowe',
    },
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
